name: Build, Test, and Publish to NuGet

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x.x

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      # Step 5: Pack the NuGet package
      - name: Pack the NuGet package
        run: dotnet pack --configuration Release --no-build --output .

      # Step 6: Clear NuGet cache
      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      # Step 7: Publish to NuGet
      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          echo "Pushing package to NuGet..."
          dotnet nuget push "./AutoMoqFixture.1.2.0.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY --skip-duplicate --verbosity detailed
