name: Build, Test, and Publish to NuGet

on:
  push:
    branches:
      - master # Default release branch

jobs:
  publish:
    name: Build, Pack & Publish
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x # Change this to match your .NET version

      # Step 3: Publish to NuGet on version change
      - name: Publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/DotNet.Testing.AutoMoqFixture/DotNet.Testing.AutoMoqFixture.csproj
          PACKAGE_NAME: AutoMoqFixture
          TAG_COMMIT: true
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
